language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/VundleVim/Vundle.vim.git
script: |
  vim -Nu <(cat << VIMRC
  set rtp+=vader.vim
  set rtp+=vundle.vim
  set rtp+=.
  " do required 'stuff'
  set nocompatible              " be iMproved, required
  filetype off                  " required
  call vundle#begin()
  " let Vundle manage Vundle, required
  Plugin 'VundleVim/Vundle.vim'
  " more plugins go HERE
  " All of your Plugins must be added before the following line
  call vundle#end()            " required
  filetype plugin indent on    " required
  VIMRC) -c 'Vader! test/*' -c 'PluginList' -c 'qa!' > /dev/null
